services:
  frontend:
    image: meeting-scheduler-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    ports:
      - "80:80"
    depends_on:
      - backend-service

  backend-service:
    image: ${DOCKER_REPO}/scheduler-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
