# Jenkins Pipeline Configuration
DOCKER_REGISTRY=docker.io
DOCKER_REPO=adwaitpatkhedkar
SONAR_PROJECT_KEY=meeting-scheduler-backend
SONAR_CREDENTIALS_ID=SonarQube
DOCKER_CREDENTIALS_ID=dockerhub-creds
